# Generated by Django 4.1 on 2023-07-19 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('M', 'Mobile'), ('L', 'Laptop'), ('TV', 'Televisions'), ('TW', 'Top Wear'), ('BW', 'Bottom Wear'), ('CM', 'Cosmetics'), ('GR', 'Grocery'), ('ST', 'Stationaries'), ('SP', 'Sports')], max_length=2),
        ),
    ]
